#!/usr/bin/env bash

test -n "$DEBUG" && set -x

#                      __ __       ___
#                     /\ \\ \    /'___`\
#                     \ \ \\ \  /\_\ /\ \
#                      \ \ \\ \_\/_/// /__
#                       \ \__ ,__\ // /_\ \
#                        \/_/\_\_//\______/
#                           \/_/  \/_____/
#                                         Algoritimos
#
#
#      Author: Ivan Lopes
#        Mail: ivan (at) 42algoritmos (dot) com (dot) br
#        Site: http://www.42algoritmos.com.br
#     License: gpl
#       Phone: +1 561 801 7985
#    Language: Shell Script
#        File: ls-branch.sh
#        Date: Qui 30 Mar 2017 08:39:13 BRT
# Description:
# ----------------------------------------------------------------------------
# Modo strict
#set -euo pipefail
# ----------------------------------------------------------------------------

##############################################################################
##############################################################################
##############################################################################

# ----------------------------------------------------------------------------
# Run!

# fbr - Interactively checkout git branches (local, remote, feature, or reflog HEADs)
# fbr – Interativamente:
#   -f  branches de feature
#   -r  branches remotos
#   -l  entradas do reflog
#   -w  diretórios de worktree  ← NOVO
fbr() {
    local branches branch
    local state="local"

    case "$1" in
        -f)
            branches=$(git branch --list '*feature*')
            ;;
        -r)
            branches=$(git branch -r)
            state="remote"
            ;;
        -l)
            branches=$(git reflog --pretty='%gD %gs' |
                sed 's/^HEAD@{[0-9]*}/HEAD@{&}/')
            state="reflog"
            ;;
        -w)
            # --porcelain facilita o parse: cada bloco começa com "worktree <path>"
            branches=$(git worktree list --porcelain |
                awk '/^worktree /{print $2}')
            state="worktree"
            ;;
        *)
            branches=$(git branch)
            ;;
    esac

    [ -z "$branches" ] && echo "Nada encontrado." && return 1

    branch=$(echo "$branches" | dmenu -i \
        -l 52 \
        -fn 'Droid Sans Mono-25' \
        -nf yellow \
        -nb black \
        -sf black \
        -sb white)

    [ -z "$branch" ] && echo "Nenhuma seleção." && return 1

    case "$state" in
        remote)
            git checkout -t "${branch##* }"
            ;;
        reflog)
            headref=$(echo "$branch" | grep -o 'HEAD@{[0-9]*}')
            git checkout "$headref"
            ;;
        worktree)
            # muda para o diretório escolhido; 'exec $SHELL' preserva a shell atual
            cd "$branch" || {
                echo "Falha ao entrar em '$branch'."
                return 1
            }
            exec "$SHELL" # opcional; mantém prompt consistente pós-cd
            ;;
        *)
            git checkout "${branch##* }"
            ;;
    esac
}

fbr "$1"
# ----------------------------------------------------------------------------
exit 0
