#!/usr/bin/env bash

test -n "$DEBUG" && set -x

#                      __ __       ___
#                     /\ \\ \    /'___`\
#                     \ \ \\ \  /\_\ /\ \
#                      \ \ \\ \_\/_/// /__
#                       \ \__ ,__\ // /_\ \
#                        \/_/\_\_//\______/
#                           \/_/  \/_____/
#                                         Algoritimos
#
#
#      Author: Ivan Lopes
#        Mail: ivan@42algoritmos.com.br
#        Site: http://www.42algoritmos.com.br
#     License: gpl
#       Phone: +1 561 801 7985
#    Language: Shell Script
#        File: mk-update-alternatives.sh
#        Date: Qua 09 Mai 2018 20:27:28 -03
# Description:
# ----------------------------------------------------------------------------
# Modo strict
#set -euo pipefail
# ----------------------------------------------------------------------------

##############################################################################
##############################################################################
##############################################################################

# ----------------------------------------------------------------------------
# Run!
MAIN=info
N=100
LOCAL=$PWD

files=(
  ngmakeidx
  ngmultidec
  ngnutmeg
  ngproc2mod
  ngsconvert
)


f=$MAIN

# Se não existe aborte
if test ! -e $LOCAL/$f
then
    echo `tput bold` `tput rev` Not Found: `tput setaf 3` "$f"  `tput sgr0`
    echo `tput bold` `tput rev` Action: `tput setf 1` "Abort!"  `tput sgr0`
    echo
    exit 1
fi
echo -n sudo update-alternatives --install /usr/local/bin/$MAIN $MAIN $LOCAL/$MAIN $N

for f in ${files[@]}; do

    # Se não existe aborte
    if test ! -e $LOCAL/$f
    then
	    echo `tput bold` `tput rev` Not Found: `tput setaf 3` "$f"  `tput sgr0`
	    echo `tput bold` `tput rev` Action: `tput setf 1` "Abort!"  `tput sgr0`
        echo
        exit 1
    fi

    echo -n ' ' --slave /usr/local/bin/$f $f $LOCAL/$f

done

# ----------------------------------------------------------------------------
exit 0
